name: Build and Push Docker Image

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set vars
        if: ${{ !env.ACT }}
        id: vars
        env:
          IMAGE_ARN: ${{ steps.meta.outputs.tags }}
        run: |
          image_version=$(echo $IMAGE_ARN | cut -d "/" -f 3)
          echo "TAG_NAME=$image_version" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: amanbhoria/start:latest
          # Change `yourusername/yourimagename` to your Docker Hub username and the name you want for your Docker image

      - name: Comment on PR with build number
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: actions/github-script@v6
        with:
            script: |
              const prNumber = context.payload.pull_request.number;
              const message = `The image tag ${process.env.TAG_NAME} has been pushed.`;
              github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: message
              });

      - name: Logout from Docker Hub
        run: docker logout